name: hebbian
channels:
  - pytorch
  - conda-forge
  - nodefaults
dependencies:
  - pytorch=1.9.0
  - torchvision=0.9.1
  - numpy=1.20.3
  - scikit-learn
  - matplotlib=3.4.2
  - tabulate=0.8.9
  - einops=0.3.2
  - eagerpy=0.29.0
  - foolbox=3.3.1
  - pandas=1.3.1
  - umap-learn=0.5.3
  - ray-core
  - ray-tune
  - pip=21.2.2
