model:
  type: GenHebb
  input_dim: 784
  hidden_dim: 100
  output_dim: 10
  learning_rule: ojas_rule
  activation: relu
  n_hebbian_layers: 1
  importance_factor: 0
  kwargs: {}
training:
  unsupervised:
    epochs: 1
    lr: 0.001
    batch_size: 64
  supervised:
    epochs: 10
    lr: 0.001
    batch_size: 64