model:
  type: GenHebb
  input_dim: 784
  hidden_dim: 100
  output_dim: 10
  learning_rule: STDP
  activation: relu
  n_hebbian_layers: 1
  importance_factor: 100
  kwargs:
    beta: 0.1
training:
  unsupervised:
    epochs: 5
    lr: 0.00001
    batch_size: 64
  supervised:
    epochs: 50
    lr: 0.001
    batch_size: 64