model:
  type: GenHebb
  input_dim: 784
  hidden_dim: 2000
  output_dim: 10
  learning_rule: STDP
  activation: tanh
  n_hebbian_layers: 2
  importance_factor: 1
  kwargs:
    beta: 0.1
training:
  unsupervised:
    epochs: 3
    lr: 0.0003
    batch_size: 128
  supervised:
    epochs: 50
    lr: 0.001
    batch_size: 64