model:
  type: GenHebb
  input_dim: 784
  hidden_dim: 2000
  output_dim: 10
  learning_rule: STDP
  activation: relu
  n_hebbian_layers: 2
  importance_factor: 10
  kwargs:
    beta: 0.1
training:
  unsupervised:
    epochs: 5
    lr: 0.00001
    batch_size: 128
  supervised:
    epochs: 100
    lr: 0.001
    batch_size: 64