model:
  type: GenHebb
  input_dim: 784
  hidden_dim: 100
  output_dim: 10
  learning_rule: STDP
  activation: tanh
  n_hebbian_layers: 2
  importance_factor: 10
  kwargs:
    beta: 0.1
training:
  unsupervised:
    epochs: 10
    lr: 0.0001
    batch_size: 128
  supervised:
    epochs: 50
    lr: 0.001
    batch_size: 64